version: '3.1'

services:

    memory:
        image: memorycache
        environment:
            - ASPNETCORE_URLS=http://+:5000
        expose: 
            - 5000

    distributed:
        image: distributedcache
        environment:
            - ASPNETCORE_URLS=http://+:4000
            - Redis__ConnectionString=redis
        expose: 
            - 4000
        depends_on:
            - redis

    redis:
        image: redis:6.2-alpine
        container_name: cache_redis
        ports:
            - 6379:6379
   
    nginx:
        image: nginx:latest
        container_name: cache_nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
          - memory
        ports:
          - 5000:5000
          - 4000:4000